services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shortlink
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
    restart: always

  nginx:
    image: nginx:1.25.4
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./volumes/nginx/conf:/etc/nginx/
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/logs:/var/log/nginx
    restart: always

  nacos:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos_container
    environment:
      - MODE=standalone
      - JVM_XMS=256m
      - JVM_XMX=256m
      - NACOS_AUTH_ENABLE=false
    ports:
      - "8964:8848"
      - "9964:9848"
      - "9965:9849"
    restart: always

  rmqnamesrv:
    image: apache/rocketmq:5.3.1
    container_name: rmqnamesrv_container
    command: sh mqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - ./volumes/rocketmq/namesrv/logs:/home/rocketmq/logs
      - ./volumes/rocketmq/namesrv/store:/home/rocketmq/store
    restart: always

  rmqbroker:
    image: apache/rocketmq:5.3.1
    container_name: rmqbroker_container
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      NAMESRV_ADDR: rmqnamesrv:9876
    volumes:
      - ./volumes/rocketmq/conf/broker.conf:/home/rocketmq/conf/broker.conf
      - ./volumes/rocketmq/broker/logs:/home/rocketmq/logs
      - ./volumes/rocketmq/broker/store:/home/rocketmq/store
    depends_on:
      - rmqnamesrv
    restart: always