server:
  port: 8003

spring:
  application:
    name: short-link-aggregation
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8964

aggregation:
  remote-url: http://127.0.0.1:${server.port}

short-link:
  group:
    max-num: 20
  user-traffic-control:
    enabled: true
    time-window: 1
    max-requests: 20
  domain:
    default: mercemay.com:8003
  demo-mode:
    enabled: false
    blacklist:
      - /api/short-link/admin/v1/group
      - /api/short-link/admin/v1/recycle-bin/remove
      - /api/short-link/admin/v1/create
      - /api/short-link/admin/v1/create/batch
      - /api/short-link/admin/v1/update
      - /api/short-link/admin/v1/user
      - /api/short-link/admin/v1/user/logout
      - /api/short-link/admin/v1/recycle-bin/save
  stats:
    locale:
      amap-key: 2b3698715ce9c881bd4bfecac7fe940f
  route:
    whitelist:
      enabled: true
      name: '知乎,哔哩哔哩,GitHub'
      details:
        - zhihu.com
        - bilibili.com
        - github.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: shortlink-stats-producer-group
    topic: shortlink-stats-topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: shortlink-stats-consumer-group

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}