server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 实现分库分表配置
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # shardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yml
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html