server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 实现分库分表配置
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # shardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yml
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: mercemay.com:8001
  stats:
    locale:
      amap-key: 2b3698715ce9c881bd4bfecac7fe940f

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml